import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/Sidebar'
import { Providers } from '@/providers/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          {/* <div>
            <Header />
          </div> */}
          <div className="flex w-screen">
            <Sidebar />

            <main className="flex-1 p-10">
              <Providers>{children}</Providers>
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
